import { Product, Store, SupplierProfile, AppSettings, Invoice, BatchCostRecord } from './types';

export const INITIAL_SUPPLIER_PROFILE: SupplierProfile = {
  name: 'Nham Nham',
  khmerName: 'ឈ្មោះអ្នកផ្គត់ផ្គង់: Nham Nham',
  address: '#342 ផ្លូវ ២៧១ សង្កាត់ស្ទឹងមានជ័យ២ ខណ្ឌមានជ័យ ភ្នំពេញ',
  phone: '016 60 92 88',
  bankName: 'ABA Bank',
  accountName: 'NANCHING BO',
  accountNumber: '004 574 599',
  currency: 'USD',
};

export const INITIAL_STORES: Store[] = [
  {
    code: 'ON-TK592',
    customerName: 'Angkor Prototype LTD.',
    shipTo: 'ON Mart St.592 TK',
    address: '#ដីឡូត៍លេខ១ ផ្លូវ ៥៩២ កែងបណ្តោយ ៦ សង្កាត់បឹងកក់ទី២ ខណ្ឌទួលគោក ភ្នំពេញ',
    phone: '099 423 599',
    creditTermsDays: 15,
  },
  {
    code: 'ON-PDK',
    customerName: 'Sambath Linda Mart',
    shipTo: 'ON Mart Phsar Derm Thkov',
    address: '#០១៥៤ ផ្លូវ១៦៣ ភូមិ៣ សង្កាត់ផ្សារដើមថ្កូវ ខណ្ឌចំការមន រាជធានីភ្នំពេញ',
    phone: '097 91 97 054',
    creditTermsDays: 15,
  },
  {
    code: 'ON-OU3',
    customerName: 'Heng Kimchy Investment',
    shipTo: 'ON Mart OU 3',
    address: 'ផ្លូវ ភូមិ៥ សង្កាត់៤ ក្រុងព្រះសីហនុ ខេត្តព្រះសីហនុ',
    phone: '096 67 69 536',
    creditTermsDays: 15,
  },
];

export const INITIAL_PRODUCTS: (Product & { subtitle?: string })[] = [
  {
    id: 'prod-2016800000025',
    barcode: '2016800000025',
    name: 'Sweet Melon Cubes 300G',
    khmerName: 'ត្រសក់ផ្អែមស្រស់',
    nameEn: 'Sweet Melon Cubes 300G',
    nameKh: 'ត្រសក់ផ្អែមស្រស់',
    subtitle: 'Fresh sweet melon cubes',
    uom: 'Pcs',
    wholesalePrice: 1.00,
    wholesalePriceUSD: 1.00,
    bom: [
      { packagingItemId: 'box-big-300g', quantity: 1 },
      { packagingItemId: 'sticker-2016800000025', quantity: 1 },
      { packagingItemId: 'skewer-wood', quantity: 1 },
    ],
  },
  {
    id: 'prod-2016800000032',
    barcode: '2016800000032',
    name: 'Baby Mango Bites',
    khmerName: 'ក្តឹបស្វាយស្រស់',
    nameEn: 'Baby Mango Bites',
    nameKh: 'ក្តឹបស្វាយស្រស់',
    subtitle: 'Sour baby mango slices',
    uom: 'Pcs',
    wholesalePrice: 0.76,
    wholesalePriceUSD: 0.76,
    bom: [
      { packagingItemId: 'box-small-std', quantity: 1 },
      { packagingItemId: 'sticker-baby-mango', quantity: 1 },
      { packagingItemId: 'skewer-wood', quantity: 1 },
    ],
  },
  {
    id: 'prod-2016800000049',
    barcode: '2016800000049',
    name: 'Jackfruit Bites 300G',
    khmerName: 'ខ្នុរសាច់លឿងស្រស់',
    nameEn: 'Jackfruit Bites 300G',
    nameKh: 'ខ្នុរសាច់លឿងស្រស់',
    subtitle: 'Sweet yellow jackfruit bulbs',
    uom: 'Pcs',
    wholesalePrice: 1.00,
    wholesalePriceUSD: 1.00,
    bom: [
      { packagingItemId: 'box-big-300g', quantity: 1 },
      { packagingItemId: 'sticker-jackfruit', quantity: 1 },
      { packagingItemId: 'skewer-wood', quantity: 1 },
    ],
  },
  {
    id: 'prod-2016800000056',
    barcode: '2016800000056',
    name: 'Guava Bites',
    khmerName: 'ត្របែកកាត់',
    nameEn: 'Guava Bites',
    nameKh: 'ត្របែកកាត់',
    subtitle: 'Crisp green guava slices',
    uom: 'Pcs',
    wholesalePrice: 0.76,
    wholesalePriceUSD: 0.76,
    bom: [
      { packagingItemId: 'box-small-std', quantity: 1 },
      { packagingItemId: 'sticker-guava', quantity: 1 },
      { packagingItemId: 'skewer-wood', quantity: 1 },
    ],
  },
  {
    id: 'prod-2016800000063',
    barcode: '2016800000063',
    name: 'Papaya Cubes',
    khmerName: 'ល្ហុងទុំស្រស់',
    nameEn: 'Papaya Cubes',
    nameKh: 'ល្ហុងទុំស្រស់',
    subtitle: 'Fresh ripe papaya cubes',
    uom: 'Pcs',
    wholesalePrice: 0.76,
    wholesalePriceUSD: 0.76,
    bom: [
      { packagingItemId: 'box-small-std', quantity: 1 },
      { packagingItemId: 'sticker-papaya', quantity: 1 },
      { packagingItemId: 'skewer-wood', quantity: 1 },
    ],
  },
  {
    id: 'prod-2016800000070',
    barcode: '2016800000070',
    name: 'Jicama Bites',
    khmerName: 'ប៉ិកួក់ស្រស់',
    nameEn: 'Jicama Bites',
    nameKh: 'ប៉ិកួក់ស្រស់',
    subtitle: 'Crisp jicama bites',
    uom: 'Pcs',
    wholesalePrice: 0.66,
    wholesalePriceUSD: 0.66,
    bom: [
      { packagingItemId: 'box-small-std', quantity: 1 },
      { packagingItemId: 'sticker-jicama', quantity: 1 },
      { packagingItemId: 'skewer-wood', quantity: 1 },
    ],
  },
  {
    id: 'prod-2016800000087',
    barcode: '2016800000087',
    name: 'Jujube Bites',
    khmerName: 'ពុទ្រាស្រស់',
    nameEn: 'Jujube Bites',
    nameKh: 'ពុទ្រាស្រស់',
    subtitle: 'Fresh crunchy jujube',
    uom: 'Pcs',
    wholesalePrice: 0.71,
    wholesalePriceUSD: 0.71,
    bom: [
      { packagingItemId: 'box-small-std', quantity: 1 },
      { packagingItemId: 'sticker-jujube', quantity: 1 },
      { packagingItemId: 'skewer-wood', quantity: 1 },
    ],
  },
  {
    id: 'prod-2016800000094',
    barcode: '2016800000094',
    name: 'Mixed Sour Fruits',
    khmerName: 'ម្ជូរចម្រុះ',
    nameEn: 'Mixed Sour Fruits',
    nameKh: 'ម្ជូរចម្រុះ',
    subtitle: 'Assorted sour fruit mix',
    uom: 'Pcs',
    wholesalePrice: 0.76,
    wholesalePriceUSD: 0.76,
    bom: [
      { packagingItemId: 'box-small-std', quantity: 1 },
      { packagingItemId: 'sticker-mixed-sour', quantity: 1 },
      { packagingItemId: 'skewer-wood', quantity: 1 },
    ],
  },
  {
    id: 'prod-2016800000100',
    barcode: '2016800000100',
    name: 'Pickled Grapes',
    khmerName: 'ទំពាំងបាយជូរត្រាំ',
    nameEn: 'Pickled Grapes',
    nameKh: 'ទំពាំងបាយជូរត្រាំ',
    subtitle: 'Sweet and tangy pickled grapes',
    uom: 'Pcs',
    wholesalePrice: 1.00,
    wholesalePriceUSD: 1.00,
    bom: [
      { packagingItemId: 'box-small-std', quantity: 1 },
      { packagingItemId: 'sticker-pickled-grapes', quantity: 1 },
      { packagingItemId: 'skewer-wood', quantity: 1 },
    ],
  },
  {
    id: 'prod-2016800000117',
    barcode: '2016800000117',
    name: 'Mixed Fresh Fruits 300G',
    khmerName: 'ផ្លែឈើស្រស់ចម្រុះ ៣០០ក្រាម',
    nameEn: 'Mixed Fresh Fruits 300G',
    nameKh: 'ផ្លែឈើស្រស់ចម្រុះ ៣០០ក្រាម',
    subtitle: 'Assorted fresh fruit bowl',
    uom: 'Pcs',
    wholesalePrice: 1.00,
    wholesalePriceUSD: 1.00,
    bom: [
      { packagingItemId: 'box-big-300g', quantity: 1 },
      { packagingItemId: 'sticker-mixed-fresh', quantity: 1 },
      { packagingItemId: 'skewer-wood', quantity: 1 },
    ],
  },
];

export const INITIAL_SETTINGS: AppSettings = {
  exchangeRate: 4050,
  defaultTubStickerKHR: 500,
  defaultColdWashKHR: 10,
  defaultFuelKHR: 8000,
  defaultCreditTermsDays: 15,
  supplierProfile: INITIAL_SUPPLIER_PROFILE,
};

// Seed sample invoices for immediate testing and billing reconciliation demo
export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-seed-1',
    invoiceNumber: 'INV-2610-001',
    storeCode: 'ON-TK592',
    customerName: 'Angkor Prototype LTD.',
    shipTo: 'ON Mart St.592 TK',
    address: '#ដីឡូត៍លេខ១ ផ្លូវ ៥៩២ កែងបណ្តោយ ៦ សង្កាត់បឹងកក់ទី២ ខណ្ឌទួលគោក ភ្នំពេញ',
    phone: '099 423 599',
    invoiceDate: '2026-10-04',
    dueDate: '2026-10-19',
    items: [
      {
        id: 'item-1',
        barcode: '2016800000025',
        name: 'Sweet Melon Cubes 300G',
        khmerName: 'ត្រសក់ផ្អែមស្រស់',
        uom: 'Pcs',
        quantity: 24,
        unitPrice: 1.00,
      },
      {
        id: 'item-2',
        barcode: '2016800000032',
        name: 'Baby Mango Bites',
        khmerName: 'ក្តឹបស្វាយស្រស់',
        uom: 'Pcs',
        quantity: 13,
        unitPrice: 0.76,
      },
      {
        id: 'item-3',
        barcode: '2016800000087',
        name: 'Jujube Bites',
        khmerName: 'ពុទ្រាស្រស់',
        uom: 'Pcs',
        quantity: 8,
        unitPrice: 0.71,
      },
    ],
    totalQuantity: 45,
    totalAmountUSD: 39.56,
    totalAmountKHR: 160218,
    status: 'paid_aba',
    paidAt: '2026-10-04T15:30:00.000Z',
    createdAt: '2026-10-04T08:30:00.000Z',
    notes: 'Morning fresh delivery to Tuol Kouk branch',
  },
  {
    id: 'inv-seed-2',
    invoiceNumber: 'INV-2610-002',
    storeCode: 'ON-PDK',
    customerName: 'Sambath Linda Mart',
    shipTo: 'ON Mart Phsar Derm Thkov',
    address: '#០១៥៤ ផ្លូវ១៦៣ ភូមិ៣ សង្កាត់ផ្សារដើមថ្កូវ ខណ្ឌចំការមន រាជធានីភ្នំពេញ',
    phone: '097 91 97 054',
    invoiceDate: '2026-10-04',
    dueDate: '2026-10-19',
    items: [
      {
        id: 'item-201',
        barcode: '2016800000049',
        name: 'Jackfruit Bites 300G',
        khmerName: 'ខ្នុរសាច់លឿងស្រស់',
        uom: 'Pcs',
        quantity: 20,
        unitPrice: 1.00,
      },
      {
        id: 'item-202',
        barcode: '2016800000094',
        name: 'Mixed Sour Fruits',
        khmerName: 'ម្ជូរចម្រុះ',
        uom: 'Pcs',
        quantity: 13,
        unitPrice: 0.76,
      },
      {
        id: 'item-203',
        barcode: '2016800000087',
        name: 'Jujube Bites',
        khmerName: 'ពុទ្រាស្រស់',
        uom: 'Pcs',
        quantity: 8,
        unitPrice: 0.71,
      },
      {
        id: 'item-204',
        barcode: '2016800000070',
        name: 'Jicama Bites',
        khmerName: 'ប៉ិកួក់ស្រស់',
        uom: 'Pcs',
        quantity: 1,
        unitPrice: 0.66,
      },
    ],
    totalQuantity: 42,
    totalAmountUSD: 36.22,
    totalAmountKHR: 146691,
    status: 'pending',
    createdAt: '2026-10-04T09:15:00.000Z',
    notes: 'Morning fresh delivery to Phsar Derm Thkov branch',
  },
  {
    id: 'inv-seed-3',
    invoiceNumber: 'INV-2610-003',
    storeCode: 'ON-OU3',
    customerName: 'Heng Kimchy Investment',
    shipTo: 'ON Mart OU 3',
    address: 'ផ្លូវ ភូមិ៥ សង្កាត់៤ ក្រុងព្រះសីហនុ ខេត្តព្រះសីហនុ',
    phone: '096 67 69 536',
    invoiceDate: '2026-10-03',
    dueDate: '2026-10-18',
    items: [
      {
        id: 'item-301',
        barcode: '2016800000025',
        name: 'Sweet Melon Cubes 300G',
        khmerName: 'ត្រសក់ផ្អែមស្រស់',
        uom: 'Pcs',
        quantity: 10,
        unitPrice: 1.00,
      },
      {
        id: 'item-302',
        barcode: '2016800000032',
        name: 'Baby Mango Bites',
        khmerName: 'ក្តឹបស្វាយស្រស់',
        uom: 'Pcs',
        quantity: 8,
        unitPrice: 0.76,
      },
      {
        id: 'item-303',
        barcode: '2016800000049',
        name: 'Jackfruit Bites 300G',
        khmerName: 'ខ្នុរសាច់លឿងស្រស់',
        uom: 'Pcs',
        quantity: 8,
        unitPrice: 1.00,
      },
      {
        id: 'item-304',
        barcode: '2016800000087',
        name: 'Jujube Bites',
        khmerName: 'ពុទ្រាស្រស់',
        uom: 'Pcs',
        quantity: 6,
        unitPrice: 0.71,
      },
      {
        id: 'item-305',
        barcode: '2016800000117',
        name: 'Mixed Fresh Fruits 300G',
        khmerName: 'ផ្លែឈើស្រស់ចម្រុះ ៣០០ក្រាម',
        uom: 'Pcs',
        quantity: 8,
        unitPrice: 1.00,
      }
    ],
    totalQuantity: 40,
    totalAmountUSD: 36.34,
    totalAmountKHR: 147177,
    status: 'pending',
    createdAt: '2026-10-03T11:00:00.000Z',
    notes: 'Sihanoukville weekly delivery batch',
  }
];

export const INITIAL_BATCH_COSTS: BatchCostRecord[] = [
  {
    id: 'batch-seed-today',
    batchNumber: 'BATCH-261004-01',
    date: '2026-10-04',
    marketSpendKHR: 90000,
    fuelExpenseKHR: 8000,
    tubStickerBOMKHR: 872,
    packagingBOMPerBoxKHR: 872,
    totalPackagingBOMCostKHR: 75864,
    coldWashBOMKHR: 10,
    exchangeRate: 4050,
    yieldItems: [
      { barcode: '2016800000025', name: 'Sweet Melon Cubes 300G', khmerName: 'ត្រសក់ផ្អែមស្រស់', boxes: 24 },
      { barcode: '2016800000032', name: 'Baby Mango Bites', khmerName: 'ក្តឹបស្វាយស្រស់', boxes: 13 },
      { barcode: '2016800000049', name: 'Jackfruit Bites 300G', khmerName: 'ខ្នុរសាច់លឿងស្រស់', boxes: 20 },
      { barcode: '2016800000094', name: 'Mixed Sour Fruits', khmerName: 'ម្ជូរចម្រុះ', boxes: 13 },
      { barcode: '2016800000087', name: 'Jujube Bites', khmerName: 'ពុទ្រាស្រស់', boxes: 16 },
      { barcode: '2016800000070', name: 'Jicama Bites', khmerName: 'ប៉ិកួក់ស្រស់', boxes: 1 },
    ],
    totalBoxesYielded: 87,
    rawFruitCostPerBoxKHR: 1034,
    fuelSharePerBoxKHR: 92,
    landedUnitCostKHR: 2008,
    landedUnitCostUSD: 0.50,
    deliveryRevenueUSD: 75.78,
    netProfitUSD: 32.85,
    netProfitKHR: 133043,
    grossMarginPercent: 43.3,
    createdAt: '2026-10-04T07:30:00.000Z',
    notes: 'Daily wholesale market run & deliveries to ON Mart stores',
  },
  {
    id: 'batch-seed-1',
    batchNumber: 'BATCH-261001-01',
    date: '2026-10-01',
    marketSpendKHR: 90000,
    fuelExpenseKHR: 8000,
    tubStickerBOMKHR: 500,
    coldWashBOMKHR: 10,
    exchangeRate: 4050,
    yieldItems: [
      { barcode: '2016800000025', name: 'Sweet Melon Cubes 300G', khmerName: 'ត្រសក់ផ្អែមស្រស់', boxes: 12 },
      { barcode: '2016800000032', name: 'Baby Mango Bites', khmerName: 'ក្តឹបស្វាយស្រស់', boxes: 10 },
      { barcode: '2016800000049', name: 'Jackfruit Bites 300G', khmerName: 'ខ្នុរសាច់លឿងស្រស់', boxes: 8 },
      { barcode: '2016800000063', name: 'Papaya Cubes', khmerName: 'ល្ហុងទុំស្រស់', boxes: 10 },
      { barcode: '2016800000100', name: 'Pickled Grapes', khmerName: 'ទំពាំងបាយជូរត្រាំ', boxes: 10 },
    ],
    totalBoxesYielded: 50,
    rawFruitCostPerBoxKHR: 1800,
    fuelSharePerBoxKHR: 160,
    landedUnitCostKHR: 2470,
    landedUnitCostUSD: 0.61,
    deliveryRevenueUSD: 44.50,
    netProfitUSD: 14.01,
    netProfitKHR: 56730,
    grossMarginPercent: 31.48,
    createdAt: '2026-10-01T07:45:00.000Z',
    notes: 'Morning wholesale market purchase from Phsar Derm Kor',
  }
];
